database:
  host: "127.0.0.1"
  port: 3306
  database: "lunarproject"
  username: "root"
  password: "1054874739"
  use-ssl: false
  allow-public-key-retrieval: true
  server-timezone: "Asia/Shanghai"
game:
  min-players: 1
  max-players: 4
  start-countdown: 10
  map-bootstrap-template: "test-map"
  vote-timeout-seconds: 20
  ready-timeout-seconds: 30
gui:
  enable: true
  menu-item-material: "COMPASS"
  menu-item-slot: 8
  auto-open-vote: true
  auto-open-reward: true
  auto-open-event: true
debug:
  combat-log: false
  dev-mob-scaling: false
classes:
  测试职业:
    max-health: 180
    yellow-bar: 135
    base-sanity: 50
stagger-thresholds:
  测试职业:
    t1: 0.75
    t2: 0.00
  Warrior:
    t1: 0.50
    t2: 0.00
  Mage:
    t1: 0.74
    t2: 0.30
  Assassin:
    t1: 0.60
    t2: 0.20
