name: LunarProject
version: '1.0-SNAPSHOT'
main: jdd.lunarProject.LunarProject
api-version: '1.21'
description: LunarProject 肉鸽流程插件
commands:
  game:
    description: LunarProject 主流程指令
    usage: /game
