name: LunarProject
version: '1.0-SNAPSHOT'
main: jdd.lunarProject.LunarProject
api-version: '1.21'
description: Roguelike gameplay loop plugin for LunarProject
commands:
  game:
    description: LunarProject game command
    usage: /game
